Extension { #name : #RMDAbstractAssignableAttributeVariableNode }

{ #category : #'*ReMobidyc-Interpreter' }
RMDAbstractAssignableAttributeVariableNode >> assign: aNumber in: aRMDInterpreter [
	^ self subclassResponsibility
]

{ #category : #'*ReMobidyc-Interpreter' }
RMDAbstractAssignableAttributeVariableNode >> assign: aNumber toNewIndividual: anInteger in: aRMDInterpreter [

	^ self subclassResponsibility
]
