Extension { #name : #RMDAbstractAssignablePropertyVariableNode }

{ #category : #'*ReMobidyc-Interpreter' }
RMDAbstractAssignablePropertyVariableNode >> assign: aNumber in: aRMDInterpreter [
	^ self subclassResponsibility
]

{ #category : #'*ReMobidyc-Interpreter' }
RMDAbstractAssignablePropertyVariableNode >> assign: aNumber toNewIndividual: anInteger in: aRMDInterpreter [

	^ self subclassResponsibility
]
